os:
  - linux
  - osx
  - windows

osx_image: xcode9.3

language: java

jdk:
  - openjdk11

jobs:
  include:
    - stage: "Tests"
      os: linux
      script: ./gradlew clean test

    - stage: "Build Native Application"
      script: ./gradlew clean buildNativeApplication
