jobs:
  include:
    - stage: "Tests"
      os: linux
      language: java
      jdk:
        - openjdk11
      script: ./gradlew clean test -PossrhUsername=test -PossrhPassword=test

    - stage: "Deploy Jar and Native Linux application and Docker"
      if: tag IS present
      os:
        - linux
      language: java
      jdk:
        - openjdk11
      script: ./gradlew clean shadowJar buildNativeApplication -PossrhUsername=test -PossrhPassword=test
      deploy:
        - provider: releases
          api_key: $GITHUB_KEY
          file_glob: true
          skip_cleanup: true
          file:
            - "*/build/libs/kafka-consumer-lag-monitoring-*.jar"
            - "*/build/dist/kafka-consumer-lag-monitoring-*.tar.gz"
          on:
            tags: true

        - provider: script
          script: ./gradlew jib -PossrhUsername=test -PossrhPassword=test
          skip_cleanup: true
          on:
            tags: true

        - provider: script
          script: ./gradlew buildAndPushNativeApplicationDockerImage -PossrhUsername=test -PossrhPassword=test
          skip_cleanup: true
          on:
            tags: true


    - stage: "Deploy Native Mac application"
      if: tag IS present
      os: osx
      osx_image: xcode9.4
      language: java
      jdk:
        - openjdk11
      script: ./gradlew clean buildNativeApplication -PossrhUsername=test -PossrhPassword=test
      deploy:
        - provider: releases
          api_key: $GITHUB_KEY
          file_glob: true
          skip_cleanup: true
          file:
              - "*/build/dist/kafka-consumer-lag-monitoring-*.tar.gz"
          on:
            tags: true
