jobs:
  include:
    - stage: "Tests"
      os: linux
      language: java
      jdk:
        - openjdk11
      script: ./gradlew clean test

    - stage: "Deploy"
      os:
        - linux
        - osx
      language: java
      osx_image: xcode9.4
      jdk:
        - openjdk11
      script: ./gradlew clean shadowJar buildNativeApplication
      deploy:
        - provider: releases
          api_key: $GITHUB_KEY
          file_glob: true
          skip_cleanup: true
          file:
            - "*/build/libs/kafka-consumer-lag-monitoring-*.jar"
            - "*/build/dist/kafka-consumer-lag-monitoring-*.tar.gz"